// api/gymcoach.js
const { GoogleGenerativeAI } = require("@google/generative-ai");

module.exports = async (req, res) => {
  const API_KEY = process.env.GEMINI_API_KEY;

  if (!API_KEY) {
    return res.status(500).json({ error: "Server API Key is missing." });
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Only POST requests allowed" });
  }

  try {
    // 1. Extract Message AND User Profile
    const { message, userProfile } = req.body;

    // 2. Build the "System Context" (Who the user is)
    const EXERCISE_LIBRARY = {
      "Back": ["Pull-Ups", "Face Pulls", "Rows", "Deadlifts", "Lat Pulldown", "Resistance Band Pull-Aparts", "Assisted Pull-Ups", "T-Bar Row (Chest Supported)", "Meadows Row", "Inverted Row", "Weighted Pull-Ups", "Pendlay Rows", "Snatch-Grip Deadlift", "Wide-Grip Muscle-Ups", "Explosive High Pulls"],
      "Biceps": ["Curls", "Hammer Curls", "Preacher Curls"],
      "Triceps": ["Pushdowns", "Skull Crushers", "Dips"],
      "Shoulders": ["Overhead Press", "Lateral Raises", "Front Raises"],
      "Legs": ["Squats", "Leg Press", "Lunges", "Leg Extensions"],
      "Chest": ["Bench Press", "Incline Press", "Flyes", "Push Ups"],
      "Mid Chest": ["Flat Barbell Bench Press", "Flat Dumbbell Bench Press", "Machine Chest Press", "Cable Chest Fly (Mid Height)", "Smith Machine Flat Bench Press", "Dumbbell Squeeze Press (Hex Press)"],
      "Lower Chest": ["Decline Barbell Bench Press", "Decline Dumbbell Press", "Chest Dips", "High to Low Cable Fly", "Smith Machine Decline Bench Press", "Decline Machine Chest Press", "Reverse-Grip Bench Press"],
      "Cardio": ["Treadmill Running", "Incline Treadmill Running", "Elliptical Machine", "Rowing Machine", "Step Machine", "Step Mill", "Bicycle Recline Walk", "Battle Rope", "Running", "Brisk Walking", "Burpees", "Jumping Jacks", "Jump Rope", "High Knee Skips", "Marching on Spot", "Squat Burpees", "Side Kick Burpee", "Slow Burpee", "Mountain Climbers", "Side Mountain Climber", "Inchworm Mountain Climbers", "Criss Cross Elbow to Knee", "Touchdown", "Jack Step", "Low Lunge Twist", "Lunge with Leg Lift", "Twist Knee Thrust", "Bodyweight Knee Thrust", "Assault Run", "Split Jump to Box", "Alternate Heel Touch Side Kick Squat", "Skater Hop Tap", "Sky Bike", "Devil Press"],
      "Calisthenics": ["Wall Push-Ups", "Incline Push-Ups", "Knee Push-Ups", "Standard Push-Ups", "Bench Dips (Knees Bent)", "Australian Rows (Inverted Rows)", "Ring Rows", "Resistance Band Assisted Pull-Ups", "Dead Hangs", "Scapular Pull-Ups"],
      "Neck": ["Neck Nods", "Side-to-Side Neck Tilts", "Neck Rotations", "Neck Circles", "Chin Tucks", "Lying Neck Flexion", "Prone Neck Extension", "Side-Lying Neck Raises", "Controlled Neck Rotations", "Neck Harness Flexion", "Neck Harness Extension", "Resistance-Band Neck Flexion/Extension", "Cable Neck Flexion/Extension", "Plate-Loaded Neck Flexion", "Wrestler Neck Bridges", "Back Bridges", "Partner-Resisted Neck Training"],
      "Rest Day": ["Rest", "Stretching"]
    };


    let systemInstruction = `
    You are GymCoach, an elite, high-energy fitness AI. 
    Your goal is to make fitness simple, fun, and aggressive.
    
    CRITICAL RULE:
    You must ONLY recommend exercises from the following allowed list. Do NOT suggest any exercise that is not in this list.
    
    ⛔ RULE ENGINE CONSTRAINT (MANDATORY):
    - You are a CHAT ASSISTANT only. You do NOT generate workout plans.
    - Workout plans are generated by the deterministic Rule Engine (not you).
    - You MUST NOT modify, override, or suggest changes to:
      • Exercise selections (these are filtered by the Rule Engine)
      • Sets, reps, rest times, RIR, or load values (these are hardcoded)
      • Injury-based exercise exclusions (these are deterministic)
    - If a user asks about their workout plan, explain the exercises but do NOT change prescription values.
    - If asked to add/remove exercises, tell them to update their profile settings.

    ALLOWED EXERCISES:
    ${JSON.stringify(EXERCISE_LIBRARY, null, 2)}

    FORMATTING RULES (STRICT):
    1. Use EMOJIS for everything. 
       - Use 🟥 for Push/Chest/Shoulders.
       - Use 🟩 for Pull/Back/Biceps.
       - Use 🟦 for Legs.
       - Use ✅ for tips.
    2. Do NOT write long paragraphs. Use Bullet points.
    3. Use **BOLD** for exercise names.
    4. Keep the format: "• **Exercise Name** – Sets x Reps".
    `;

    if (userProfile) {
      // Handle undefined injuries safely
      const injuries = userProfile.injuries && userProfile.injuries.length > 0
        ? userProfile.injuries.join(", ")
        : "None";

      // Format equipment access for better readability
      const equipmentMap = {
        'full_gym': 'Full Gym Access (barbells, dumbbells, machines, cables)',
        'basic_equipment': 'Basic Equipment (dumbbells, bench, resistance bands)',
        'dumbbells_only': 'Dumbbells Only',
        'cables_only': 'Cables Only',
        'bodyweight_only': 'Bodyweight Only (no equipment)'
      };
      const equipment = equipmentMap[userProfile.equipment] || userProfile.equipment || 'Not specified';

      // Format goal for better readability
      const goalMap = {
        'lose_fat': 'Lose Fat (caloric deficit)',
        'build_muscle': 'Build Muscle (caloric surplus)',
        'recomp': 'Body Recomposition (maintain calories, build muscle while losing fat)',
        'general_fitness': 'General Fitness (stay healthy, active, and strong)',
        'strength': 'Strength Training'
      };
      const goal = goalMap[userProfile.goal] || userProfile.goal || 'Not specified';

      // Calculate age if date_of_birth is available
      let ageInfo = userProfile.age ? `${userProfile.age} years old` : '';
      if (userProfile.date_of_birth) {
        const birthDate = new Date(userProfile.date_of_birth);
        const today = new Date();
        const calculatedAge = Math.floor((today - birthDate) / (365.25 * 24 * 60 * 60 * 1000));
        ageInfo = `${calculatedAge} years old`;
      }

      systemInstruction += `
        ═══════════════════════════════════════════════════════════
        🏋️ USER PROFILE - ${userProfile.name || userProfile.username || 'Athlete'}
        ═══════════════════════════════════════════════════════════
        
        📊 PERSONAL INFO:
        - Name: ${userProfile.name || 'Not provided'}
        - Age: ${ageInfo || 'Not provided'}
        - Gender: ${userProfile.gender || 'Not specified'}
        
        📏 BODY METRICS:
        - Height: ${userProfile.height ? userProfile.height + ' cm' : 'Not provided'}
        - Weight: ${userProfile.weight ? userProfile.weight + ' kg' : 'Not provided'}
        ${userProfile.stats && userProfile.stats.bmr ? `- BMR (Basal Metabolic Rate): ${Math.round(userProfile.stats.bmr)} calories/day` : ''}
        ${userProfile.stats && userProfile.stats.tdee ? `- TDEE (Total Daily Energy Expenditure): ${Math.round(userProfile.stats.tdee)} calories/day` : ''}
        ${userProfile.stats && userProfile.stats.target_calories ? `- Target Calories: ${Math.round(userProfile.stats.target_calories)} calories/day` : ''}
        
        🎯 FITNESS PROFILE:
        - Primary Goal: ${goal}
        - Experience Level: ${userProfile.experience || userProfile.experience_level || 'Beginner'}
        - Training Frequency: ${userProfile.frequency || userProfile.training_frequency || 'Not specified'} days per week
        - Equipment Access: ${equipment}
        
        ⚠️ INJURIES/LIMITATIONS:
        - ${injuries}
        ${injuries !== 'None' ? '  ⚡ CRITICAL: Avoid or modify exercises that stress these areas!' : ''}
        
        ═══════════════════════════════════════════════════════════
        
        💡 COACHING INSTRUCTIONS:
        Based on this profile, you MUST:
        
        1. **Goal-Specific Programming:**
           ${userProfile.goal === 'lose_fat' || userProfile.goal === 'Lose Fat' ?
          '   - Focus on higher intensity, shorter rest periods (30-60s)\n   - Include metabolic conditioning and cardio\n   - Emphasize compound movements for maximum calorie burn\n   - Mention their caloric deficit target if discussing nutrition' :
          userProfile.goal === 'build_muscle' || userProfile.goal === 'Build Muscle' ?
            '   - Focus on hypertrophy range (8-12 reps, 60-90s rest)\n   - Progressive overload is KEY\n   - Emphasize time under tension and controlled tempo\n   - Mention their caloric surplus target if discussing nutrition' :
            userProfile.goal === 'recomp' ?
              '   - Balance strength training with some conditioning\n   - Focus on progressive overload while maintaining calories\n   - Emphasize protein intake (high protein at maintenance calories)' :
              '   - Provide balanced programming for overall health and fitness'}
        
        2. **Equipment-Appropriate Exercises:**
           - ONLY recommend exercises they can do with: ${equipment}
           ${userProfile.equipment === 'bodyweight_only' ? '   - Focus on calisthenics, progressive overload through variations' : ''}
           ${userProfile.equipment === 'dumbbells_only' ? '   - Get creative with dumbbell variations, unilateral work' : ''}
        
        3. **Experience-Appropriate Complexity:**
           ${userProfile.experience === 'beginner' || userProfile.experience_level === 'beginner' ?
          '   - Keep it SIMPLE. Focus on fundamental movement patterns\n   - Emphasize form over weight\n   - Avoid overly complex programming' :
          userProfile.experience === 'advanced' || userProfile.experience_level === 'advanced' ?
            '   - Can handle advanced techniques (drop sets, supersets, etc.)\n   - Assume good mind-muscle connection\n   - Can discuss periodization and advanced concepts' :
            '   - Moderate complexity, can introduce some advanced techniques'}
        
        4. **Injury Considerations:**
           ${injuries !== 'None' ?
          `   - ALWAYS consider their ${injuries} when recommending exercises\n   - Suggest modifications or alternatives for problematic movements\n   - Prioritize joint-friendly variations` :
          '   - No specific injury concerns, but always emphasize proper form'}
        
        5. **Training Frequency Context:**
           - They train ${userProfile.frequency || userProfile.training_frequency || 3} days/week
           ${(userProfile.frequency || userProfile.training_frequency) <= 3 ?
          '   - Recommend full-body or upper/lower splits\n   - Focus on compound movements for efficiency' :
          (userProfile.frequency || userProfile.training_frequency) >= 5 ?
            '   - Can handle body part splits or push/pull/legs\n   - More volume and frequency per muscle group' :
            '   - Upper/lower or push/pull/legs works well'}
        
        6. **Personalization:**
           - Address them by name when appropriate: ${userProfile.name || userProfile.username || 'champ'}
           - Reference their specific stats when relevant (age, weight, etc.)
           - Make recommendations feel tailored to THEIR situation
        
        ═══════════════════════════════════════════════════════════
        `;
    } else {
      systemInstruction += `
      
      ⚠️ NO PROFILE DATA AVAILABLE
      Ask them to complete their profile in the Onboarding section for personalized advice.
      Without their stats, you can only give general recommendations.
      `;
    }

    // 3. Connect to Gemini
    const genAI = new GoogleGenerativeAI(API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    // 4. Combine System Instruction + User Question
    const finalPrompt = `${systemInstruction}\n\nUSER QUESTION: "${message}"`;

    const result = await model.generateContent(finalPrompt);
    const response = await result.response;
    const text = response.text();

    return res.status(200).json({ reply: text });

  } catch (error) {
    console.error("Gemini Error:", error);
    return res.status(500).json({ error: error.message || "Failed to generate response." });
  }
};